name: Linux

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -yq libgtest-dev libboost-program-options-dev rapidjson-dev

    - name: Build GTest
      run: cmake -E make_directory gtest && cd gtest && cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} /usr/src/gtest && cmake --build . -j -v && sudo cmake --install .

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G Ninja $GITHUB_WORKSPACE

    - name: Build the Project
      working-directory: build
      run: cmake --build . -j -v

    - name: Run the Tests
      working-directory: build
      run: ctest --output-on-failure
