name: Windows

on: [push, pull_request]

jobs:
  Windows:
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86', 'x64']
        libs: ['shared', 'static']
        config: ['Debug', 'Release']

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set config variables
      id: set-variables
      shell: pwsh
      run: |
        echo "::set-output name=vcpkg_triplet::${{ matrix.arch }}-windows$(if ('${{ matrix.libs }}' -eq 'static') { '-static' })"
        echo "::set-output name=build_shared::$(if ('${{ matrix.libs }}' -eq 'shared') { 'ON' } else { 'OFF' })"
        echo "::set-output name=build_arch::$(if ('${{ matrix.arch }}' -eq 'x64') { 'X64' } else { 'Win32' })"

    - name: Cache vcpkg and dependencies
      uses: actions/cache@v2
      id: cache-vcpkg
      with:
        path: vcpkg/
        key: vcpkg-${{ steps.set-variables.outputs.vcpkg_triplet }}

    - name: Install Dependencies
      if: ${{ !steps.cache-vcpkg.outputs.cache-hit }}
      shell: pwsh
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install
        ./vcpkg install boost-program-options rapidjson gtest --triplet ${{ steps.set-variables.outputs.vcpkg_triplet }}

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_SHARED_LIBS=${{ steps.set-variables.outputs.vcpkg_triplet }} -DBUILD_SHARED_LIBS=${{ steps.set-variables.outputs.build_shared }} -G "Visual Studio 16 2019" -A ${{ steps.set-variables.outputs.build_arch }} ${{ github.workspace }}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{ matrix.config }}

    - name: Test
      working-directory: build/
      run: ctest -C ${{ matrix.config }} --output-on-failure
